config/routes.rb
BlueSource::Application.routes.draw do
  get 'api/subordinates'
  get 'api/manager'

  resources :titles

  get 'admin/index'
  namespace :admin do
    resources :departments, only: :index
    resources :titles
  end

  resources :employees do
    resources :vacations, only: [:index, :create, :update, :destroy] do
      collection do
        get 'view'
        post 'requests'
      end
      member do
        delete 'cancel'
      end
    end
    resources :project_histories, path: 'projects'
    patch 'preferences'
  end

  resources :departments, only: [:destroy, :new, :create, :update, :edit] do
    get 'sub_departments'
    get 'employees'
  end

  resources :projects, only: [:index, :show, :create, :update, :edit] do
    get 'leads'
  end

  get 'login', to: 'welcome#login', as: :login
  get 'logout', to: 'welcome#logout', as: :logout
  post 'login', to: 'welcome#validate', as: :check_login
  post 'issue', to: 'welcome#issue', as: :issue
  post 'search', to: 'welcome#search_employee', as: :search
  post 'login_issue', to: 'welcome#login_issue', as: :login_issue

  resource :directory, only: [:show], controller: 'directory' do
    resources :employees, only: [:index], action: 'directory'
  end

  resource :calendar, only: [:index] do
    get '/', to: 'calendar#index'
    get '/report', to: 'calendar#report'
  end

  root 'employees#index'

end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  before_action :require_manager_login, except: :view_vacation
  before_action :set_user, only: [:index, :edit, :vacation, :update, :view_vacation]
  
  #Only manager of employee can edit vacation, employee info, or update info.
  before_action :check_manager_status, only: [:edit, :vacation, :update]
  
  #Manager of employee or employee can view themselves.
  before_action :check_employee_is_current_user_or_manager, only: [:index, :view_vacation, :update]
  
  #Validate date parameters.
  before_action :validate_start_date, only: [:new, :update]
  before_action :validate_roll_on_date, only: [:new, :update]
  before_action :validate_roll_off_date, only: [:new, :update]
  
  layout :set_layout
  
  def index
    if request.referer == root_url+"employee/vacation/#{@employee.id}"
      @prev_page = 3
    end
    @prev_page = 2 if flash[:project] == true
    
    respond_to do |format|
      format.json {render json: @employee}
      format.html
    end
  end
  
  def edit
  end
  
  def new
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to :root, flash: {notice: "Employee added successfully."}
    else
      redirect_to :root, flash: {error: @employee.errors.full_messages}
    end 
  end
  
  def all
    respond_to do |format|
      format.json {render json: current_user.all_subordinates.to_json({
        include: [
          {:manager => {:only => [:first_name,:last_name]}}, 
          {:project => {:only => :name}}], 
        only: [:id, :first_name, :last_name, :role, :manager_id, :project_id, :location, :status]
      })}
    end
  end
  
  def vacation
    respond_to do |format|
      format.json {render json: @employee.vacations}
      format.html
    end
  end
  
  def update
    if @employee.update(employee_params)
      redirect_to @employee, flash: {notice: "Employee successfully updated.", project: !employee_params[:project_id].nil?}
    else
      redirect_to :back, flash: {error: @employee.errors.full_messages.first}
    end
  end
  
  private
  
  def set_user
    @employee = Employee.find(params[:id])
    @title = @employee.display_name
  end
  
  def check_manager_status
    redirect_to :root unless current_user.above? @employee or current_user.admin?
  end
  
  def check_employee_is_current_user_or_manager
    redirect_to :root unless current_user == @employee or current_user.above? @employee or current_user.is_upper_management?
  end
  
  def set_layout
    case action_name
    when "index"
      "view_resource"
    when "all"
      "resource"
    end
  end
  
  def validate_start_date
    validate_date(employee_params[:start_date]) unless employee_params[:start_date].blank?
  end
  
  def validate_roll_on_date
    validate_date(employee_params[:roll_on_date])
  end
  
  def validate_roll_off_date
    validate_date(employee_params[:roll_off_date])
  end
  
  def employee_params
    allowed_params = [:first_name, :last_name, :project_id, :start_date, :office_phone, :level, :location, :department, :cell_phone, :email, :im_name, :im_client, :team_lead_id, :roll_on_date, :roll_off_date]
    allowed_params += [:role, :manager_id, :status, :additional_days] if current_user.is_upper_management?
    param_hash = params.require(:employee).permit(allowed_params)
    param_hash.each {|key,val| param_hash[key]=val.downcase if key=='first_name' or key=='last_name'} unless param_hash.blank?
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :require_login

  # Sets the employee
  before_action :set_employee, only: %i(show update preferences projects)
  before_action :employee_must_be_current_user, only: :preferences
  before_action :require_manager_login, except: %i(directory preferences)

  before_action :can_edit, only: :update
  before_action :can_view, only: :show

  # Validate date parameters.
  before_action :validate_start_date, only: %i(create update)

  layout :set_layout

  def show
    @prev_page = 3 if request.referer == employee_vacations_url(@employee.id)
    @prev_page = 2 if flash[:project] == true

    @current_project = ProjectHistory.employee_current_projects(@employee).first

    respond_to do |format|
      format.json { render json: @employee }
      format.html
    end
  end

  def directory
    respond_to do |format|
      format.json
    end
  end

  def preferences
    preferences = params.require(:employee).permit(preferences: :resourcesPerPage)
    if @employee.update(preferences)
      redirect_to @employee, flash: { success: 'Employee successfully updated.' }
    else
      redirect_to @employee, flash: { error: @employee.errors.full_messages }
    end
  end

  def create
    @employee = Employee.new(employee_params)
    unless current_user.can_add? @employee
      redirect_to :root, flash: { error: 'You do not have permission to add this employee.' }
      return
    end

    if @employee.save
      redirect_to :root, flash: { success: 'Employee added successfully.' }
    else
      redirect_to root_url(employee: params['employee']), flash: { error: @employee.errors.full_messages }
    end
  end

  def index
    @employee = Employee.new(employee_params) if params['employee'].present?
    @modal_title = 'Add Consultant'
    @resource_for_angular = 'employee'
    respond_to do |format|
      format.html
      format.json
    end
  end

  def update
    if @employee.update(employee_params)
      redirect_to @employee, flash: { success: 'Employee successfully updated.', project: employee_params[:project_id].present? }
    else
      redirect_to @employee, flash: { error: @employee.errors.full_messages }
    end
  end

  private

  def set_employee
    @employee = Employee.find(params[:id] || params[:employee_id])
    @title = @employee.display_name
  end

  def set_layout
    case action_name
    when 'show'
      'view_resource'
    when 'index'
      'resource'
    end
  end

  def validate_start_date
    validate_date(employee_params[:start_date]) unless employee_params[:start_date].blank?
  end

  def employee_params
    allowed_params = %i(username first_name last_name project_id start_date office_phone level location cell_phone email im_name im_client team_lead_id scheduled_hours_start scheduled_hours_end project_comments title_id)
    allowed_params += %i(role manager_id status additional_days bridge_time) if current_user.upper_management?
    param_hash = params.require(:employee).permit(allowed_params, department_id: [])
    param_hash[:department_id] = param_hash[:department_id].reject { |val| val.empty? }.last if param_hash.key?(:department_id)
    param_hash.each { |key, val| param_hash[key] = val.downcase if %w(first_name last_name).include?(key) } unless param_hash.blank?
  end

  # Permissions

  def can_view
    return if current_user.can_view? @employee
    redirect_to :root, flash: { error: 'You do not have permission to view this employee.' }
  end

  def can_edit
    return if current_user.can_edit? @employee
    redirect_to :root, flash: { error: 'You do not have permission to edit this employee.' }
  end

  def employee_must_be_current_user
    return if current_user == @employee
    redirect_to :root, flash: { error: 'You do not have permission to edit preferences for this employee.' }
  end
end

app/helpers/employee_helper.rb
require 'vacation_helper'

module EmployeeHelper
  def time_ago_exact(on_date)
    time_array = []
    seconds = Date.current.to_time - on_date.to_time
    years = (seconds / (60*60*24*365)).floor
    time_array << pluralize(years,'year') unless years == 0
    seconds_left = seconds % (60*60*24*365)
    months = (seconds_left / (60*60*24*31)).floor
    time_array << pluralize(months,'month') unless months == 0
    seconds_left = seconds_left % (60*60*24*31)
    weeks = (seconds_left / (60*60*24*7)).floor
    time_array << pluralize(weeks,'week') unless weeks == 0
    seconds_left = seconds_left % (60*60*24*7)
    days = (seconds_left / (60*60*24)).floor
    time_array << pluralize(days,'day') unless days == 0 and (years > 0 or weeks > 0 or months > 0 or days > 0)
    return time_array.join(", ")
  end
  
  def accrual_rates(years_of_employment)
    months_in_year = 12.0
    case years_of_employment
    when 0..2 then 10.0/months_in_year
    when 3..5 then 15.0/months_in_year
    else 20.0/months_in_year
    end
  end
  
  def accrued_vacation_days_on_date(date,anniversary_date=nil)
    #Calculate total months from previous fiscal new year to date.
    months = date.distance_in_months(date.previous_fiscal_new_year) + 1
    years_with_orasi = 1
    
    #Calculate total months from anniversary to date.
    unless anniversary_date.nil?
      if anniversary_date > date.previous_fiscal_new_year
        months = date.distance_in_months(anniversary_date)
        months += 1 if anniversary_date.day == 1
      end
      #Calculate the years the employee has been with Orasi
      years_with_orasi = date.distance_in_years(anniversary_date)
      
      years_with_orasi = 1 if years_with_orasi <= 0
      
      #Calculate anniversary date for this year.
      anniversary_months = anniversary_date.day == 1 ? 1 : 0
      anniversary_date = anniversary_date.change(day:1,year: date.current_fiscal_year - (anniversary_date.month >= 5 ? 1 : 0))
      anniversary_date = anniversary_date + 1.month
      anniversary_months += date.distance_in_months(anniversary_date) + 1
      if anniversary_months > 0
        return ((accrual_rates(years_with_orasi-1)*(months - anniversary_months)) + (accrual_rates(years_with_orasi)*anniversary_months)).round(2)
      elsif anniversary_months == 0 
        years_with_orasi -= 1
      end
    end
    (accrual_rates(years_with_orasi)*(months)).round(2)
    
  end
  
  def special_vacation_round(days)
    _split_max_days = days.divmod(1)
    if _split_max_days.last >= 0.5
      return _split_max_days.first + 0.5
    end
    
    _split_max_days.first
  end

  def active_subordinates
    self.subordinates.where.not(status: 'Inactive')
  end
end

app/views/employees/_add_form.html.erb
<% @employee ||= Employee.new %>
<% @employee.role = 'Base' %>
<%= render 'employees/form' %>

app/views/employees/_form.html.erb
<%= form_for @employee, url: employee_path(@employee), html: {class: "form-horizontal", role: "form"} do |f| %>
<div class="form-group">
	<%= f.label :username, nil, class: "control-label" do %>
	<%= image_tag 'logo.png', class: "image image-responsive", width: "65px"%> username
	<% end %>
	<%= f.text_field :username, value: "#{@employee.username unless @employee.username.blank?}", class: "form-control", required: true %>
</div>
<div class="form-group">
	<%= f.label :first_name, nil, class: "control-label" %>
	<%= f.text_field :first_name, value: "#{@employee.first_name.capitalize unless @employee.first_name.blank?}", class: "form-control", required: true %>
</div>
<div class="form-group">
	<%= f.label :last_name, nil, class: "control-label" %>
	<%= f.text_field :last_name, value: "#{@employee.last_name.capitalize unless @employee.last_name.blank?}", class: "form-control", required: true %>
</div>
<div class="form-group">
	<%= f.label :title, nil, class: "control-label" %>
	<%= select :employee, :title_id, Title.all.collect {|t| [ t.name, t.id ] }, {include_blank: true}, class: "form-control" %>
</div>
<% if current_user.upper_management? %>
<div class="form-group">
	<%= f.label :role, nil, class: "control-label" do %>
	<%= image_tag 'logo.png', class: "image image-responsive", width: "65px"%> role
	<% end %>
	<%= f.select :role, Employee.roles, {}, class: "form-control", required: true %>
</div>
<div class="form-group">
	<%= f.label :manager, nil, class: "control-label"%>
	<%= select :employee, :manager_id, Employee.all.order(:first_name).where.not(id: @employee).find_all {|f| f.manager_or_higher? }.collect {|f| [f.display_name, f.id]}, { include_blank: true }, class: "form-control" %>
</div>
<div class="form-group">
	<%= f.label :status, nil, class: "control-label" %>
	<%= f.select :status, Employee.statuses, {}, class: "form-control" %>
</div>
<% end %>
<% if current_user.role.in? ["Company Admin", "Department Admin"] %>
<div class="form-group">
	<%= f.label :bridge_time, nil, class: "control-label" %>
	<%= f.number_field :bridge_time, class: "form-control" %>
</div>
<% end %>
<div class="form-group">
	<%= f.label :location, class: "control-label"%>
	<%= f.select :location, Employee.locations, { include_blank: true }, class: "form-control" %>
</div>
<div class="form-group">
	<%= f.label :start_date, nil, class: "control-label" %>
	<%= f.date_field :start_date, class: "form-control", placeholder: "YYYY-MM-DD", pattern: '\d{4}-\d{2}-\d{2}', title: "YYYY-MM-DD" %>
</div>
<div class="form-group">
	<%= f.label :cell_phone, nil, class: "control-label" %>
	<%= f.phone_field :cell_phone, class: "form-control" %>
	<span role="alert" class="errormsg"></span>
</div>
<div class="form-group">
	<%= f.label :office_phone, nil, class: "control-label" %>
	<%= f.phone_field :office_phone, class: "form-control" %>
	<span role="alert" class="errormsg"></span>
</div>
<div class="form-group">
	<%= f.label :email, nil, class: "control-label" %>
	<%= f.text_field :email, class: "form-control" %>
</div>
<div class="form-group">
	<%= f.label :im_name, "IM Name", class: "control-label" %>
	<%= f.text_field :im_name, class: "form-control" %>
</div>
<div class="form-group">
	<%= f.label :im_client, "IM Client", class: "control-label" %>
	<%= f.select :im_client, Employee.im_client_types, {include_blank: true}, class: "form-control" %>
</div>
<% if current_user.role.in? ["Department Head", "Department Admin", "Company Admin"] %>
<div class="form-group">
	<%= f.label :department, 'Department', class: "control-label" %>
	<% unless current_user.department.blank? %>
		<% if @employee.department.blank? %>
			<% path_to_highest_dept = current_user.department.find_path_to_highest_department %>
	 		<% path_to_highest_dept.reverse.each do |dept_id| %>
	 			<% dept = Department.find(dept_id) %>
	 			<% if dept == current_user.department or dept.above?(current_user.department) %>
	 			  <%= f.select :department_id, options_from_collection_for_select(Department.where(id: dept_id), 'id', 'name', dept_id), {}, class: "form-control", name: "employee[department_id][]" %>
	 			<% else %>
	 			  <%= f.select :department_id, options_from_collection_for_select(Department.where(department_id: dept.parent_department), 'id', 'name', dept_id), {include_blank: true}, class: "form-control", name: "employee[department_id][]" %>
	 			<% end %>
	 		<% end %>
			<% unless current_user.department.sub_departments.blank? %>
					<%= f.select :department_id, options_from_collection_for_select(current_user.department.sub_departments, 'id', 'name'), {include_blank: true}, class: "form-control", name: "employee[department_id][]" %>
			<% end %>
		<% else %>
			<% path_to_highest_dept = @employee.department.find_path_to_highest_department %>
	 		<% path_to_highest_dept.reverse.each do |dept_id| %>
	 			<% dept = Department.find(dept_id) %>
	 			<% if dept == current_user.department or dept.above?(current_user.department) %>
	 			  <%= f.select :department_id, options_from_collection_for_select(Department.where(id: dept_id), 'id', 'name', dept_id), {}, class: "form-control", name: "employee[department_id][]" %>
	 			<% else %>
	 			  <%= f.select :department_id, options_from_collection_for_select(Department.where(department_id: dept.parent_department), 'id', 'name', dept_id), {include_blank: true}, class: "form-control", name: "employee[department_id][]" %>
	 			<% end %>
	 		<% end %>
	 		<% unless @employee.department.sub_departments.blank? %>
	 			<%= f.select :department_id, options_from_collection_for_select(@employee.department.sub_departments, 'id', 'name'), {include_blank: true}, class: "form-control", name: "employee[department_id][]" %>
	 		<% end %>
		<% end %>
	<% else %>
		<% if @employee.department.blank? %>
			<%= f.select :department_id, options_from_collection_for_select(Department.where(department_id: nil), 'id', 'name'), {include_blank: true}, class: "form-control", name: "employee[department_id][]" %>
		<% else %>
			<% path_to_highest_dept = @employee.department.find_path_to_highest_department %>
	 		<% path_to_highest_dept.reverse.each do |dept_id| %>
	 			<% dept = Department.find(dept_id) %>
	 			<%= f.select :department_id, options_from_collection_for_select(Department.where(department_id: dept.parent_department), 'id', 'name', dept_id), {include_blank: true}, class: "form-control", name: "employee[department_id][]" %>
	 		<% end %>
	 		<% unless @employee.department.sub_departments.blank? %>
	 			<%= f.select :department_id, options_from_collection_for_select(@employee.department.sub_departments, 'id', 'name'), {include_blank: true}, class: "form-control", name: "employee[department_id][]" %>
	 		<% end %>
		<% end %>
	<% end %>
</div>
<% end %>
<div class="form-group modal-footer">
	<%= button_tag "Close", type: "button", class: "btn btn-default", data: {dismiss: "modal"} if @in_modal %>
	<%= f.submit class: "btn btn-primary", "data-loading-text" => "Saving..."%>
</div>
<% end %>

app/views/employees/_project_form.html.erb
<%= form_for @employee do |f| %>
<% unless @employee.project.blank? %>
<% @project_team_leads = Project.find(@employee.project.id).leads %>
<% else %>
<% @project_team_leads = []%>
<% end %>
<%= hidden_field "form", "in_modal", value: true %>
<div class="form-group">
    <%= f.label :project, class: "control-label" %>
    <%= select :employee, :project_id, Project.order("lower(name) asc").collect {|p| [p.name, p.id]}, {include_blank: true}, class: "form-control" %>
</div>
<div class="form-group <%= "hidden" if @project_team_leads.count <= 1 %>" id="team_lead_section">
	<%= f.label :team_lead, class: "control-label" %>
	<%= f.select :team_lead_id, @project_team_leads.collect {|p| [p.display_name, p.id]} , {include_blank: @project_team_leads.count > 1}, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label 'Roll On Date', 'Roll On Date', class: "control-label" %>
    <%= f.date_field :roll_on_date, class: "form-control", placeholder: "YYYY-MM-DD", pattern: '\d{4}-\d{2}-\d{2}', title: "YYYY-MM-DD" %>
</div>
<div class="form-group">
    <%= f.label :roll_off_date, 'Roll Off Date', class: "control-label" %>
    <%= f.date_field :roll_off_date, class: "form-control", placeholder: "YYYY-MM-DD", pattern: '\d{4}-\d{2}-\d{2}', title: "YYYY-MM-DD" %>
</div>
<div class="form-group">
    <%= f.label :project_scheduled_hours, 'Project Scheduled Hours', class: "control-label" %>
    <div id="project-hours">
    <%= time_field_tag "employee[scheduled_hours_start]", :scheduled_hours_start, class: "form-control", value: (@employee.scheduled_hours_start unless @employee.scheduled_hours_start.blank?) %> to 
    <%= time_field_tag "employee[scheduled_hours_end]", :scheduled_hours_end, class: "form-control", value: (@employee.scheduled_hours_end unless @employee.scheduled_hours_end.blank?) %>
    </div>
</div>
<div class="form-group">
    <%= f.label :project_comments, 'Project Comments', class: "control-label" %>
    <%= f.text_area :project_comments, class: "form-control" %>
</div>
<div class="form-group modal-footer">
    <%= button_tag "Close", type: "button", class: "btn btn-default", data: {dismiss: "modal"} %>
    <%= f.submit class: "btn btn-primary", "data-loading-text" => "Saving..."%>
</div>
<% end %>

app/views/employees/edit.html.erb
<h1><%= @employee.display_name %></h1>
<% if @employee.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
		<ul>
			<% @employee.errors.full_messages.each do |msg| %>
			<li>
				<%= msg %>
			</li>
			<% end %>
		</ul>
	</div>
<% end %>
<div class="panel-group">
	<div class="panel panel-primary">

		<div class="panel-heading">
			<h4 class="panel-title">General Data</h4>
		</div>
		<div id="generalData" class="panel-collapse collapse in">
			<div class="panel-body">
				<%= render "form" %>
			</div>
		</div>
	</div>

</div>
<%= link_to "Cancel", @employee, class: "btn btn-link"%>

app/views/employees/show.html.erb
<!-- General info panel -->
<!-- Header information -->
<% content_for 'panel_title_1' do %>General Info<% end %>
<% content_for 'panel_heading_1' do %>
<%= button_tag "Manage", class: "btn btn-default btn-xs pull-right no-collapse", data: {toggle: "modal", target: "#modal_1"} if current_user.can_edit? @employee %>
<% end %>
<!-- /Header information -->

<!-- Modal content -->
<!-- Content for modal -->
<% content_for "modal_header_1" do %>Manage Employee<% end %>

<% content_for "modal_content_1" do %>
<%@in_modal=true%>
<%= render "form" %>
<% end %>

<!-- General info body -->
<% content_for 'panel_body_1' do %>
<table class="table">
	<tr>
		<td class="logo-row"><%= image_tag 'logo.png', class: "image image-responsive", width: "65px"%> username:</td>
		<td><%= @employee.username unless @employee.username.blank? %></td>
	</tr>
	<tr>
		<td class="logo-row"><%= image_tag 'logo.png', class: "image image-responsive", width: "65px"%> role:</td>
		<td><%= @employee.role unless @employee.role.blank? %></td>
	</tr>
	<tr>
		<td>Title:</td>
		<td><%= @employee.title unless @employee.title.blank? %></td>
	</tr>
	<tr>
		<td>Manager:</td>
		<td><%= link_to @employee.manager.display_name, "#{@employee.manager.id}" unless @employee.manager.blank? %></td>
	</tr>
	<tr>
		<td>Status:</td>
		<td><%= @employee.status %></td>
	</tr>
	<tr>
		<td>Location:</td>
		<td><%= @employee.location %></td>
	</tr>
	<tr>
		<td>Start Date:</td>
		<td><%= @employee.start_date.strftime("%B %e, %Y") unless @employee.start_date.blank? %></td>
	</tr>
	<tr>
		<td>Time with Orasi:</td>
		<td><%= time_ago_exact(@employee.start_date) unless @employee.start_date.blank? or @employee.start_date >= Time.now %></td>
	</tr>
	<tr>
		<td>Cell Phone:</td>
		<td><%= @employee.cell_phone unless @employee.cell_phone.blank? %></td>
	</tr>
	<tr>
		<td>Office Phone:</td>
		<td><%= @employee.office_phone unless @employee.office_phone.blank?%></td>
	</tr>
	<tr>
		<td>Email:</td>
		<td><%= mail_to @employee.email unless @employee.email.blank? %></td>
	</tr>
	<tr>
		<td>IM Username:</td>
		<td><%= @employee.im_name unless @employee.im_name.blank? %></td>
	</tr>
	<tr>
		<td>IM Client:</td>
		<td><%= @employee.im_client unless @employee.im_client.blank? %></td>
	</tr>
	<tr>
		<td>Department:</td>
		<td><%= @employee.department.name unless @employee.department.blank? %></td>
	</tr>
</table>
<% end %>
<!-- /General info body -->

<!-- Project info panel -->
<!-- Project info head -->
<% content_for 'panel_title_2' do %>Project Info<% end %>
<% content_for 'panel_heading_2' do %>
<% if current_user.can_edit? @employee %>
<div class="pull-right">
	<%= link_to "Manage", employee_project_histories_path(@employee), class: "btn btn-default btn-xs no-collapse" %>
</div>
<% end %>
<% end %>
<!-- /Project info head -->

<!-- Project info body -->
<% content_for 'panel_body_2' do %>
<table class="table">
	<tr>
		<td>Project:</td>
		<td><%= (@current_project.blank? || @current_project.project.blank?) ? "Not billable" : @current_project.project.name %></td>
	</tr>
	<tr>
		<td>Project Lead:</td>
		<td><%= @current_project.lead.display_name unless (@current_project.blank? or @current_project.lead.blank?) %></td>
	</tr>
	<tr>
		<td>Lead Office Phone:</td>
		<td><%= @current_project.lead.office_phone unless (@current_project.blank? or @current_project.lead.blank?) %></td>
	</tr>
	<tr>
		<td>Roll On Date:</td>
		<td><%= @current_project.roll_on_date unless (@current_project.blank? or @current_project.roll_on_date.blank?) %></td>
	</tr>
	<tr>
		<td>Roll Off Date:</td>
		<td><%= @current_project.roll_off_date unless (@current_project.blank? or @current_project.roll_off_date.blank?) %></td>
	</tr>
	<tr>
		<td>Project Scheduled Hours:</td>
		<td>
			<% unless @current_project.blank? or (@current_project.scheduled_hours_start.blank? and @current_project.scheduled_hours_end.blank?) %>
			<%= @current_project.scheduled_hours_start.to_s(:scheduled_time) unless @current_project.scheduled_hours_start.blank? %> -
			<%= @current_project.scheduled_hours_end.to_s(:scheduled_time) unless @current_project.scheduled_hours_end.blank? %>
			<% end %>
		</td>
	</tr>
	<tr>
		<td>Project Memo:</td>
		<td><%= @current_project.memo unless @current_project.blank? %></td>
	</tr>
</table>
<% end %>
<!-- /Project info body -->
<!-- /Project info panel -->

<!-- Time off panel -->
<!-- Time off head -->
<% content_for 'panel_title_3' do %>Time Off Info<% end %>
<% content_for 'panel_heading_3' do %>
<div class="pull-right">
	<% if current_user.can_view? @employee %>
	<%= link_to "View", view_employee_vacations_path(@employee), class: "btn btn-default btn-xs no-collapse" %>
	<% end %>
	<% if current_user.can_edit? @employee %>
	<%= link_to "Manage", employee_vacations_path(@employee), class: "btn btn-default btn-xs no-collapse"  %>
	<% end %>
</div>
<% end %>
<!-- /Time off head -->

<!-- Time off body -->
<% content_for 'panel_body_3' do %>
<table class="table">
	<tr>
		<td>Sick Days Taken:</td>
		<td><%= "#{@employee.sick_days_taken.prettify}/#{@employee.max_sick_days}" %></td>
	</tr>
	<tr>
		<td>Vacation Days Taken:</td>
      <td><%= "#{@employee.vacation_days_taken(Date.new(calculate_fiscal_year)).prettify}/#{@employee.max_vacation_days(Date.current)}" %></td>
    </tr>
	<tr>
		<td>Floating Holidays Taken:</td>
		<td><%= "#{@employee.floating_holidays_taken.prettify}/#{@employee.max_floating_holidays}" %></td>
	</tr>
</table>
<% end %>
<!-- /Time off body -->
<!-- /Time off panel -->

<% content_for :footer do %>
<%= link_to "Back", :root %>
<% end %>

<%= render 'modals/modal_group' %>
<%= render "panel_group" %>