config/routes.rb
BlueSource::Application.routes.draw do
  get 'api/subordinates'
  get 'api/manager'

  resources :titles

  get 'admin/index'
  namespace :admin do
    resources :departments, only: :index
    resources :titles
  end

  resources :employees do
    resources :vacations, only: [:index, :create, :update, :destroy] do
      collection do
        get 'view'
        post 'requests'
      end
      member do
        delete 'cancel'
      end
    end
    resources :project_histories, path: 'projects'
    patch 'preferences'
  end

  resources :departments, only: [:destroy, :new, :create, :update, :edit] do
    get 'sub_departments'
    get 'employees'
  end

  resources :projects, only: [:index, :show, :create, :update, :edit] do
    get 'leads'
  end

  get 'login', to: 'welcome#login', as: :login
  get 'logout', to: 'welcome#logout', as: :logout
  post 'login', to: 'welcome#validate', as: :check_login
  post 'issue', to: 'welcome#issue', as: :issue
  post 'search', to: 'welcome#search_employee', as: :search
  post 'login_issue', to: 'welcome#login_issue', as: :login_issue

  resource :directory, only: [:show], controller: 'directory' do
    resources :employees, only: [:index], action: 'directory'
  end

  resource :calendar, only: [:index] do
    get '/', to: 'calendar#index'
    get '/report', to: 'calendar#report'
  end

  root 'employees#index'

end

app/models/vacation.rb
class Vacation < ActiveRecord::Base
  include VacationHelper
  
  scope :vacations_in_range, ->(start_date,end_date) do 
    where(%Q(
       (vacations.start_date BETWEEN :filter_start_date and :filter_end_date) or
       (vacations.end_date BETWEEN :filter_start_date and :filter_end_date) or
       (:filter_start_date BETWEEN vacations.start_date and vacations.end_date)
     ),filter_start_date: start_date, filter_end_date: end_date)
  end
  
  belongs_to :employee
  belongs_to :manager, class_name: "Employee"
  
  before_validation :set_business_days
  
  validates :vacation_type, presence: true, inclusion: { in: ->(vacation){vacation.class.types} }
  validates :date_requested, :start_date, :end_date, :employee, :manager, presence: true
  validates :business_days, presence: true, numericality: {greater_than: 0}
  validate :employee_is_not_inactive
  validate :minimum_and_maximum_dates
  validate :end_date_cannot_be_before_start_date
  validate :vacation_not_already_included
  validate :reason_present_if_other
  validate :vacation_not_added_before_start_date
  validate :pdo_type_must_be_other_if_contractor
  
  def self.types
    ['Sick','Vacation','Floating Holiday','Other']
  end
  
  def pdo_type_must_be_other_if_contractor
    if self.employee.status == 'Contractor' && self.vacation_type != 'Other'
      self.reason = "Contractor #{self.vacation_type}"
      self.vacation_type = 'Other'
      self.save
    end
  end
  
  def pdo_taken(fiscal_year=Date.current.year)
    if fiscal_year > end_date.current_fiscal_year or fiscal_year < start_date.current_fiscal_year
      return 0.0
    end
    date_range = (start_date..end_date)
    if Date.new(fiscal_year).fiscal_new_year.in? date_range
      return Vacation.calc_business_days_for_range(start_date,start_date.fiscal_new_year-1)
    elsif Date.new(fiscal_year).previous_fiscal_new_year.in? date_range
      return Vacation.calc_business_days_for_range(end_date.previous_fiscal_new_year,end_date) - (half_day==true ? 0.5 : 0)
    else
      return business_days
    end
  end

  def pending?
    self.status == 'Pending'
  end

  private
  
  def vacation_not_added_before_start_date
    errors.add(:start_date, "is before employee's start date.") if !(employee.start_date.blank? || start_date.blank?) && (employee.start_date > start_date)
  end
  
  def reason_present_if_other
    errors.add(:base, "Reason must be present for vacation type 'Other'.") if self.reason.blank? && self.vacation_type == 'Other'
  end
  
  def end_date_cannot_be_before_start_date
    errors.add(:end_date, "can't be before start date.") unless end_date.blank? || start_date.blank? || end_date >= start_date
  end
  
  def set_business_days
    #Calculates the correct number of business days taken.
    return if self.start_date.blank? || self.end_date.blank?
    
    self.business_days = Vacation.calc_business_days_for_range(self.start_date,self.end_date)
    self.business_days -= 0.5 if self.half_day
  end
  
  def vacation_not_already_included
    Rails.logger.error "Start date was blank." if self.start_date.blank?
    Rails.logger.error "End date was blank." if self.end_date.blank?
    return if self.start_date.blank? or self.end_date.blank?
    
    (start_date..end_date).each do |date|
      start_date_count = (half_day and date == end_date) ? 0.5 : 1
      days_taken = Employee.find(employee_id).vacations.vacations_in_range(date,date).where.not(id: id).inject(start_date_count) do |sum, v|
        sum + ((v.end_date == date and v.half_day) ? 0.5 : 1)
      end
      return errors.add(:date_range, "includes date already included for PDO.") if days_taken > 1
    end
    
  end
  
  # def pdo_days_taken
  #   Rails.logger.error "Start date was blank." if self.start_date.blank?
  #   Rails.logger.error "End date was blank." if self.end_date.blank?
  #   return if self.start_date.blank? or self.end_date.blank? or self.vacation_type == "Other"
  #
  #   unless validate_pto(self.start_date,self.end_date)
  #     errors.add(:base, "Adding this PTO would put employee over alloted #{self.vacation_type.downcase} days.")
  #   end
  # end
  
  def minimum_and_maximum_dates
    return if date_requested.blank? || start_date.blank? || end_date.blank?
    
    minimum_date = Date.new(2000)
    maximum_date = Date.new(2100)

    errors.add(:date_requested, "is before the minimum date of #{minimum_date}.") unless minimum_date < date_requested
    errors.add(:start_date, "is before the minimum date of #{minimum_date}.") unless minimum_date < start_date
    errors.add(:end_date, "is before the minimum date of #{minimum_date}.") unless minimum_date < end_date

    errors.add(:date_requested, "is after the maximum date of #{maximum_date}.") unless maximum_date > date_requested
    errors.add(:start_date, "is before the maximum date of #{maximum_date}.") unless maximum_date > start_date
    errors.add(:end_date, "is before the maximum date of #{maximum_date}.")unless maximum_date > end_date
  end
  
  def employee_is_not_inactive
    errors.add("Employee's status", 'was inactive.') if employee.status == 'Inactive'
  end
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  before_action :require_login
  before_action :require_manager_login, except: %i(view requests update cancel)

  before_action :set_vacation, only: %i(destroy update cancel)
  before_action :set_employee
  before_action :set_fiscal_year_and_vacations, only: %i(view index)
  before_action :check_edit_permissions, only: %i(index update create destroy)
  before_action :check_view_permissions, only: %i(view requests cancel)

  def index
    respond_to do |format|
      format.json { render json: @employee.vacations }
      format.html
    end
  end

  def create
    @vacation = Vacation.new(vacation_params)

    respond_to do |format|
      if @vacation.save
        warning_msg = check_vacation_days
        if warning_msg.present?
          format.html { redirect_to employee_vacations_path(@employee), flash: { warning: warning_msg, created: @vacation.id } }
        else
          format.html { redirect_to employee_vacations_path(@employee, fy: @vacation.start_date.current_fiscal_year), flash: { success: 'Time off successfully saved.', created: @vacation.id } }
        end
      else
        format.html { redirect_to employee_vacations_path(@employee), flash: { error: @vacation.errors.full_messages } }
      end
    end
  end

  def update
    respond_to do |format|
      if @vacation.update(vacation_params)
        send_confirmation_email
        warning_msg = check_vacation_days
        if warning_msg.present?
          format.html { redirect_to employee_vacations_path(@employee, fy: @vacation.start_date.current_fiscal_year), flash: { warning: warning_msg, created: @vacation.id } }
        else
          format.html { redirect_to employee_vacations_path(@employee, fy: @vacation.start_date.current_fiscal_year), flash: { success: 'Time off successfully updated.', created: @vacation.id } }
        end
      else
        format.html { redirect_to :back, flash: { error: @vacation.errors.full_messages, created: @vacation.id } }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @vacation.destroy
        send_confirmation_email
        format.html { redirect_to :back, flash: { success: 'Time off successfully deleted.' } }
      else
        format.html { redirect_to :back, flash: { error: @vacation.errors.full_messages, created: @vacation.id } }
      end
    end
  end

  def cancel
    unless @vacation.status == 'Pending'
      redirect_to :back, flash: { error: 'Time off is accepted.  You cannot modify the vacation from here.  Please speak with your manager.' }
      return
    end

    destroy
  end

  def requests
    if current_user.manager.blank?
      redirect_to :back, flash: { error: "You don't have a manager, so you cannot request time off." }
      return
    end

    @vacation = Vacation.new(vacation_params.merge(employee_id: current_user.id, manager_id: current_user.manager.id, status: 'Pending'))
    respond_to do |format|
      if @vacation.save
        VacationRequestMailer.request_email(current_user, current_user.manager, @vacation, params[:memo], params['cc'] == '1' ? current_user.email : nil).deliver
        format.html { redirect_to view_employee_vacations_path(current_user, fy: @vacation.start_date.current_fiscal_year), flash: { success: 'Time off successfully saved.', created: @vacation.id } }
      else
        format.html { redirect_to :back, flash: { error: @vacation.errors.full_messages } }
      end
    end
  end

  private

  def check_vacation_days
    return nil unless @vacation.vacation_type == 'Vacation'
    fiscal_year_of_start_date = @vacation.start_date.current_fiscal_year
    fiscal_year_of_end_date = @vacation.end_date.current_fiscal_year
    warnings = []

    if @employee.vacations.where(vacation_type: 'Vacation', status: [nil, '']).reduce(0.0) { |sum, vacation| sum += vacation.pdo_taken(fiscal_year_of_start_date) } > @employee.max_vacation_days(Date.new(fiscal_year_of_start_date))
      warnings << "Time off saved, but this is borrowing days from fiscal year #{fiscal_year_of_start_date + 1}."

      if fiscal_year_of_start_date != fiscal_year_of_end_date
        warnings << "Time off saved, but this is borrowing days from fiscal year #{fiscal_year_of_end_date + 1}."
      end
    end

    warnings
  end

  def send_confirmation_email
    if params['confirm'].present?
      VacationRequestMailer.confirm_email(current_user, @employee, @vacation, params['confirm'] == 'true').deliver
    elsif @employee.manager.present? && @vacation.pending?
      VacationRequestMailer.cancel_email(current_user, @employee.manager, @vacation).deliver
    end
  end

  def set_fiscal_year_and_vacations
    @fyear = params['fy'].blank? ? Vacation.calculate_fiscal_year : params['fy'].to_i
    starting_year = @employee.start_date.blank? ? Date.current.year : @employee.start_date.fiscal_new_year.year
    unless @employee.vacations.count == 0
      first_logged_vacation_year = @employee.vacations.order(start_date: :asc).first.start_date.year
      starting_year = first_logged_vacation_year < starting_year ? first_logged_vacation_year : starting_year
    end
    @fy_options = (starting_year..Date.current.year + 1).map { |date| ["Fiscal Year #{date}", date] }.reverse
    @fy_vacations = @employee.vacations
      .where('start_date >= :prev_fy_new_yr and start_date < :fy_new_yr or end_date >= :prev_fy_new_yr and end_date < :fy_new_yr', prev_fy_new_yr: Date.new(@fyear).previous_fiscal_new_year, fy_new_yr: Date.new(@fyear).fiscal_new_year)
      .order("#{params[:sort].blank? ? :start_date : params[:sort]} #{params[:rev] != 'true' ? 'ASC' : 'DESC'}")
    @any_with_pending_status = @fy_vacations.where(status: 'Pending').count > 0
  end

  def check_edit_permissions
    return if current_user.can_edit? @employee
    redirect_to :root, flash: { error: 'You have insufficient privileges to edit time off for that employee.' }
  end

  def check_view_permissions
    return if current_user.can_view? @employee
    redirect_to :root, flash: { error: 'You have insufficient privileges to view time off for that employee.' }
  end

  def set_vacation
    @vacation = Vacation.find(params[:id])
  rescue
    respond_to do |format|
      format.html { redirect_to :back, flash: { error: 'Time off not found in BlueSource.' } }
    end
  end

  def set_employee
    @employee = Employee.find(params[:employee_id])
  end

  def vacation_params
    initial_params = if params[:id].present?
                       params[params[:id]]
                     elsif params['new'].blank?
                       params
                     else
                       params['new']
                     end

    all_params = initial_params.require(:vacation).permit(:date_requested, :start_date, :end_date, :vacation_type, :business_days, :employee_id, :half_day, :reason, :status)
    all_params[:manager_id] = current_user.id
    all_params[:employee_id] = params[:employee_id]
    all_params[:status] = ''
    all_params[:half_day] = false if all_params[:half_day].blank?
    all_params
  end
end

app/helpers/vacation_helper.rb
module VacationHelper
  #Calculates the fiscal year of the given date.
  def calculate_fiscal_year(date = Date.current)
    date >= Date.new(date.year, 05, 01) ? date.year+1 : date.year
  end
  
  #Calculates the next fiscal new year date for the given date.
  def fiscal_new_year_date(date = Date.current)
    Date.new(calculate_fiscal_year(date),05,01)
  end

  #Calculates the number of business days used for a date range.
  def calc_business_days_for_range(start_date, end_date)
    total = 0
    return total if start_date.blank? or end_date.blank?
    (start_date..end_date).each do |date|
      total += 1 unless date.saturday? or date.sunday? or date.is_orasi_holiday?
    end
    return total
  end

  def self.included(base)
    base.extend(VacationHelper)
  end
end

app/views/vacations/_form_request.html.erb
<%= form_for :vacation, url: requests_employee_vacations_path(@employee), html: {role: "form", id: "request-form"} do |f| %>
  <%=f.hidden_field :date_requested, value: Date.current %>
  <div class="form-group">
    <strong>Requested on <%=Date.current%></strong>
  </div>
  <div class="form-group">
    <%= f.label :start_date, class: "control-label" %>
    <%= f.date_field :start_date, class: "date-field form-control start-date", placeholder: "YYYY-MM-DD", required: true, pattern: '\d{4}-\d{2}-\d{2}', title: "YYYY-MM-DD" %>
  </div>
  <div class="form-group">
    <%= f.label :end_date, class: "control-label" %>
    <%= f.date_field :end_date, class: "date-field form-control end-date", placeholder: "YYYY-MM-DD", required: true, pattern: '\d{4}-\d{2}-\d{2}', title: "YYYY-MM-DD" %>
  </div>
  <div class="form-group">
    <%= f.label :vacation_type %>
    <%= f.select :vacation_type, @employee.status != "Contractor" ? Vacation.types - ["Other"] : Vacation.types - ["Other","Floating Holiday"], {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :half_day %>
    <%= f.check_box :half_day, class: "half-day" %>
    <label for="cc_check_box">CC me on this email.</label>
    <input id="cc_check_box" name="cc" type="checkbox" value="1">
  </div>
  <div class="form-group">
    <%= f.label :business_days %>
    <div class="business-days"><strong></strong></div>
  </div>
  <div>
  	<%= f.label :memo %>
  	<%= text_area_tag :memo, nil, class: "form-control" %>
  </div>
  <%= f.submit "Request time off", class: "btn btn-primary", "data-loading-text" => "Requesting..."%>
<% end %>

app/views/vacations/index.html.haml
%div
  %h1
    Time Off Details for
    = @employee.display_name

  = render 'notification_section'
  = render 'vacation_summary'

  = form_tag employee_vacations_path(@employee), method: :post, id: 'vacation_form' do
    %input{ name: '_method', type: 'hidden'}
      .table-responsive
        %table.table.table-bordered.table-hover.table-condensed
          %tr
            %th
              = link_to 'Date Requested',employee_vacations_path(@employee, sort: :date_requested, rev: params[:rev]!='true', fy: params[:fy])
              = render partial: 'application/ascending_descending_icon_nojs', locals: { predicate: params[:sort] == 'date_requested', forward: params[:rev]!='true', numeric: true }
            %th
              = link_to 'Start Date',employee_vacations_path(@employee, sort: :start_date, rev: params[:rev]!='true', fy: params[:fy])
              = render partial: 'application/ascending_descending_icon_nojs', locals: { predicate: params[:sort] == 'start_date', forward: params[:rev]!='true', numeric: true }
            %th
              = link_to 'End Date',employee_vacations_path(@employee, sort: :end_date, rev: params[:rev]!='true', fy: params[:fy])
              = render partial: 'application/ascending_descending_icon_nojs', locals: {predicate: params[:sort] == 'end_date', forward: params[:rev]!='true', numeric: true}
            %th
              = link_to 'Total Business Days',employee_vacations_path(@employee, sort: :business_days, rev: params[:rev]!='true', fy: params[:fy])
              = render partial: 'application/ascending_descending_icon_nojs', locals: {predicate: params[:sort] == 'business_days', forward: params[:rev]!='true', numeric: true}
            %th
              = link_to 'Type',employee_vacations_path(@employee, sort: :vacation_type, rev: params[:rev]!='true', fy: params[:fy])
              = render partial: 'application/ascending_descending_icon_nojs', locals: {predicate: params[:sort] == 'vacation_type', forward: params[:rev]!='true'}
            %th Half Day
            - if @fy_vacations.count > 0
              - unless @fy_vacations.count == @fy_vacations.where(status: 'Pending').count
                %th Edit
                %th Delete
              - if @any_with_pending_status
                %th Accept?
            - else
              %th Save
          - @fy_vacations.each do |vacation|
            %tr.vacation-row{class: (if flash[:success] then 'success' elsif flash[:warning] then 'warning' else 'danger' end if !flash[:created].blank? and vacation.id == flash[:created]) }
              - %w(date_requested start_date end_date).each do |field|
                %td.edit-field
                  %span= vacation.send(field).to_s(:long) unless vacation.send(field).blank?
                  %input.date-field.hidden{ type: 'date', placeholder: 'YYYY-MM-DD', pattern: '\d{4}-\d{2}-\d{2}', title: 'YYYY-MM-DD', name: "#{vacation.id}[vacation][#{field}]", value: vacation.send(field), class: field.dasherize }
              %td.business-days
                %strong
              %td.edit-field
                - reason_content = "<input name='#{vacation.id}[vacation][reason]' value='#{vacation.reason}'>"
                %span{ 'data-title' => 'Reason', 'data-content' => vacation.reason, 'data-placement' => 'left', class: ('reason-show' if vacation.vacation_type == 'Other')}= vacation.vacation_type
                = select_tag "#{vacation.id}[vacation][vacation_type]", options_for_select(Vacation.types,vacation.vacation_type), data: {title: 'Reason', content: reason_content, placement: 'top', html: true, animation: false}, class: 'vacation-type form-control hidden'
              %td.check-field
                .hidden{'data-toggle' => 'buttons'}
                  %label.btn.btn-xs.btn-primary{class: ('active' if vacation.half_day)}
                    = check_box_tag "#{vacation.id}[vacation][half_day]", true, vacation.half_day, class: 'half-day'
                    Half Day
              - unless @fy_vacations.count == @fy_vacations.where(status: 'Pending').count
                %td
                  - unless vacation.pending?
                    = link_to "#", class: "edit-btn" do
                      = submit_tag "Update Time Off", class: "hidden btn btn-xs btn-primary", data: {method: :patch, "form-action" => employee_vacation_path(@employee,vacation)}
                      %span.glyphicon.glyphicon-pencil
                %td.icon-field
                  - unless vacation.pending?
                    = link_to employee_vacation_path(vacation.employee, vacation), method: :delete, data: {confirm: "Are you sure you want to delete this?"} do
                      %button.hidden.edit-field.btn.btn-xs.btn-danger Remove
                      %span.glyphicon.glyphicon-trash
              - if @any_with_pending_status
                %td
                  - if vacation.status == "Pending"
                    = link_to '#' do
                      = tag :span, class: "approval-btn glyphicon glyphicon-ok pull-left", style: "color:green", data: {method: :patch, "form-action" => employee_vacation_path(vacation.employee, vacation, :confirm => true)}
                    = link_to employee_vacation_path(vacation.employee, vacation, :confirm => false), method: :delete do
                      %span.glyphicon.glyphicon-remove.pull-right
          %tr
            %td
              %input{ type: 'date', name: 'new[vacation][date_requested]', value: Time.now.strftime('%F'), placeholder: 'YYYY-MM-DD', pattern: '\d{4}-\d{2}-\d{2}', title: 'YYYY-MM-DD' }
            %td
              %input.date-field.start-date{ type: 'date', name: 'new[vacation][start_date]', placeholder: 'YYYY-MM-DD', pattern: '\d{4}-\d{2}-\d{2}', title: 'YYYY-MM-DD' }
            %td
              %input.date-field.end-date{ type: 'date', name: 'new[vacation][end_date]', placeholder: 'YYYY-MM-DD', pattern: '\d{4}-\d{2}-\d{2}', title: 'YYYY-MM-DD' }
            %td.business-days
              %strong
            %td
              - new_reason_content = "<input name='new[vacation][reason]'>"
              = select_tag 'new[vacation][vacation_type]', options_for_select(Vacation.types), data: {title: 'Reason', content: new_reason_content, placement: 'bottom', html: true, animation: false}, class: 'vacation-type form-control'
            %td
              %div{'data-toggle' => 'buttons'}
                %label.btn.btn-xs.btn-primary
                  = check_box_tag 'new[vacation][half_day]', true, false, class: 'half-day'
                  Half Day
            %td{colspan: 2}
              %input.btn.btn-primary.btn-xs{type: 'submit', value: 'Save Time Off', 'data-fo rm-action' => employee_vacations_path(@employee), 'data-method' => :post, 'data-loading-text' => 'Saving...'}
      = link_to 'Back', employee_path(@employee)
- content_for 'modal_header_1' do
  = "Time off details for FY#{@fyear}"
- content_for 'modal_content_1' do
  = render 'details'
= render 'modals/modal_group'

app/views/vacations/view.html.erb
<h1>Time Off Details for <%= @employee.display_name %></h1>
<%= render "notification_section" %>
<%= render "vacation_summary" %>
<% if @fy_vacations.count > 0 %>
<div class="table-responsive">
<table class="table table-responsive table-bordered">
	<tr>
		<th>
          <%= link_to 'Date Requested',view_employee_vacations_path(@employee, sort: :date_requested, rev: params[:rev]!='true', fy: params[:fy])  %>
          <%= render partial: 'application/ascending_descending_icon_nojs', locals: {predicate: params[:sort] == 'date_requested', forward: params[:rev]!='true', numeric: true} %>
        </th>
		<th>
          <%= link_to 'Start Date',view_employee_vacations_path(@employee, sort: :start_date, rev: params[:rev]!='true', fy: params[:fy])  %>
          <%= render partial: 'application/ascending_descending_icon_nojs', locals: {predicate: params[:sort] == 'start_date', forward: params[:rev]!='true', numeric: true} %>
        </th>
		<th>
          <%= link_to 'End Date',view_employee_vacations_path(@employee, sort: :end_date, rev: params[:rev]!='true', fy: params[:fy])  %>
          <%= render partial: 'application/ascending_descending_icon_nojs', locals: {predicate: params[:sort] == 'end_date', forward: params[:rev]!='true', numeric: true} %>
        </th>
		<th>
          <%= link_to 'Total Business Days',view_employee_vacations_path(@employee, sort: :business_days, rev: params[:rev]!='true', fy: params[:fy])  %>
          <%= render partial: 'application/ascending_descending_icon_nojs', locals: {predicate: params[:sort] == 'business_days', forward: params[:rev]!='true', numeric: true} %>
        </th>
		<th>
          <%= link_to 'Type',view_employee_vacations_path(@employee, sort: :vacation_type, rev: params[:rev]!='true', fy: params[:fy])  %>
          <%= render partial: 'application/ascending_descending_icon_nojs', locals: {predicate: params[:sort] == 'vacation_type', forward: params[:rev]!='true', numeric: false} %>
        </th>
		<% if @any_with_pending_status %>
		<th>
          <%= link_to "Status",view_employee_vacations_path(@employee, sort: :status, rev: params[:rev]!='true', fy: params[:fy])%>
          <%= render partial: 'application/ascending_descending_icon_nojs', locals: {predicate: params[:sort] == 'status', forward: params[:rev]!='true', numeric: false} %>
        </th>
		<th>Cancel</th>
		<% end %>
	</tr>
	<% @fy_vacations.each do |vacation| %>
	<tr class="<%= if flash[:success] then "success" elsif flash[:warning] then "warning" else "danger" end if !flash[:created].blank? and vacation.id == flash[:created]  %>">
		<td><%= vacation.date_requested.to_s(:long) unless vacation.date_requested.blank? %></td>
		<td><%= vacation.start_date.to_s(:long) unless vacation.start_date.blank? %></td>
		<td><%= vacation.end_date.to_s(:long) unless vacation.end_date.blank? %></td>
		<td><%= vacation.business_days.prettify %></td>
		<td>
			<span data-title="Reason" data-content="<%= vacation.reason %>" data-placement="left" class="<%= "reason-show" if vacation.vacation_type == 'Other' %>">
				<%= vacation.vacation_type%>
			</span>
		</td>
		<% if @any_with_pending_status %>
		<td><%= vacation.status %></td>
		<td>
			<% if vacation.status == "Pending" %>
			<%= link_to cancel_employee_vacation_path(current_user, vacation), method: :delete do %>
				<span class="glyphicon glyphicon-remove"></span>
			<% end %>
			<% end %>
		</td>
		<% end %>
	</tr>
	<% end %>
</table>
</div>
<% else %>
<h5>No PDO used.</h5>
<% end %>
<div>
	<% if current_user == @employee %>
	<% unless @employee.manager.blank? %>
	<%= mail_to(@employee.manager.email, class:"btn btn-default") do %>
		<span class="glyphicon glyphicon-envelope"></span> Email manager
	<% end %>
	<% end %>
	<%= button_tag "Request time off", class: "btn btn-primary", data: {target: "#modal_2", toggle: "modal"} %>
	<% end %>
</div>

<%# Modal stuff %>
<% content_for "modal_header_1" do %>
	Time off details for <%= "FY#{@fyear}"%>
<% end %>
<% content_for "modal_content_1" do %>
	<%= render "details" %>
<% end %>
<% content_for "modal_header_2" do %>
	Request PDO
<% end %>
<% content_for "modal_content_2" do %>
	<%= render "form_request" %>
<% end %>
<%= render "modals/modal_group"%>