config/routes.rb
BlueSource::Application.routes.draw do
  get 'api/subordinates'
  get 'api/manager'

  resources :titles

  get 'admin/index'
  namespace :admin do
    resources :departments, only: :index
    resources :titles
  end

  resources :employees do
    resources :vacations, only: [:index, :create, :update, :destroy] do
      collection do
        get 'view'
        post 'requests'
      end
      member do
        delete 'cancel'
      end
    end
    resources :project_histories, path: 'projects'
    patch 'preferences'
  end

  resources :departments, only: [:destroy, :new, :create, :update, :edit] do
    get 'sub_departments'
    get 'employees'
  end

  resources :projects, only: [:index, :show, :create, :update, :edit] do
    get 'leads'
  end

  get 'login', to: 'welcome#login', as: :login
  get 'logout', to: 'welcome#logout', as: :logout
  post 'login', to: 'welcome#validate', as: :check_login
  post 'issue', to: 'welcome#issue', as: :issue
  post 'search', to: 'welcome#search_employee', as: :search
  post 'login_issue', to: 'welcome#login_issue', as: :login_issue

  resource :directory, only: [:show], controller: 'directory' do
    resources :employees, only: [:index], action: 'directory'
  end

  resource :calendar, only: [:index] do
    get '/', to: 'calendar#index'
    get '/report', to: 'calendar#report'
  end

  root 'employees#index'

end

app/controllers/calendar_controller.rb
# rubocop:disable Style/LineLength, Style/MethodLength, Style/CyclomaticComplexity, Style/ClassLength
class CalendarController < ApplicationController
  include VacationHelper

  before_action :require_login
  helper_method :get_orasi_holiday, :change_month

  def report
    errors = []
    if filter_params[:start_date].blank?
      errors << 'Start date is required for reporting'
    end
    if filter_params[:end_date].blank?
      errors << 'End date is required for reporting'
    end
    if filter_params[:end_date] < filter_params[:start_date]
      errors << 'Start date must be before end date.'
    end

    unless errors.blank?
      redirect_to :back, flash: { error: errors }
      return
    end

    @include_reasons = filter_params[:include_reasons].to_i == 1

    @vacation_types = Vacation.types.map { |type| type if (filter_params[type.downcase.gsub(' ', '_').to_sym].to_i == 1) }.compact

    @vacations = Vacation
      .where(vacation_type: @vacation_types)
      .vacations_in_range(filter_params['start_date'], filter_params['end_date'])
    @vacations = @vacations.where.not(status: 'Pending') if filter_params[:include_pending].to_i == 0

    unless filter_params['department'].blank? || filter_params['department'] == 'Select All'
      @vacations = @vacations.where(employee_id: Department.find(filter_params['department']).employees.pluck(:id))
    end

    unless params[:sort].blank?
      case params[:sort].to_sym
      when :name
        @vacations = @vacations.joins(:employee).order('employees.first_name')
      when :department
        @vacations = @vacations.joins(:employee).joins('LEFT JOIN departments on employees.department_id = departments.id').order('departments.name')
      else
        @vacations = @vacations.order(params[:sort])
      end
    end

    @vacations = @vacations.reverse_order if params['rev'] == 'true'
    @report_vacations = get_report_vacations(@vacations)
    respond_to do |format|
      format.html do
        page_number = params['pgn'].to_i
        page_number = 1 if page_number <= 0
        @active_page = page_number - 1

        resources_per_page = if current_user.preferences.blank? || current_user.preferences['resourcesPerPage'].blank?
                               15
                             else
                               current_user.preferences['resourcesPerPage'].to_i
                             end

        @filter = OpenStruct.new(filter_params)
        @page_count = (@vacations.count.to_f / resources_per_page).ceil
        set_pagination
        @vacations = @vacations.limit(resources_per_page).offset(resources_per_page * (page_number - 1))
        @report_vacations = get_report_vacations(@vacations)

      end
      format.json
      format.csv
    end
  end

  def index
    @max_entries_per_day = 4
    @all_months = (1..12).map { |month_no| [Date.new(2014, month_no, 1).strftime('%B'), month_no] }
    if params[:year].present? && params[:month].present?
      @starting_date = Date.new(params[:year].to_i, params[:month].to_i, 1)
    else
      @starting_date = Date.current.change(day: 1)
    end

    @filter_types = ['all']
    @selected_filter_type = 'all'

    unless current_user.subordinates.blank?
      @filter_types << 'direct'
      @selected_filter_type = 'direct'
    end

    unless current_user.department.blank?
      @filter_types << 'department'
      @selected_filter_type = 'department'
    end

    @selected_filter_type = params[:filter] unless params[:filter].blank?

    case @selected_filter_type
    when 'all'
      @pdo_times = Vacation.all
    when 'department'
      @pdo_times = Vacation.where(employee_id: current_user.department.employees.pluck(:id))
    when 'direct'
      @pdo_times = Vacation.where(employee_id: current_user.subordinates.pluck(:id) + [current_user.id])
    end

    if @pdo_times.present?
      @selectable_years = (@pdo_times.order(start_date: :asc).first.start_date.year..@pdo_times.order(end_date: :desc).first.end_date.year)
    else
      @selectable_years = (Date.current.year - 2..Date.current.year + 2)
    end

    @disabled_prev_month = (@starting_date - 1.month).year < @selectable_years.first
    @disabled_next_month = (@starting_date + 1.month).year > @selectable_years.last

    @pdo_times = @pdo_times.vacations_in_range(@starting_date.beginning_of_month, @starting_date.end_of_month)
  end

  def change_month(no_months)
    months_to_add = no_months.months
    if params[:month].blank? || params[:year].blank?
      prev_date = Date.current
    else
      prev_date = Date.new(params[:year].to_i, params[:month].to_i, 1)
    end
    new_date = prev_date + months_to_add
    new_params = params.merge(month: new_date.month, year: new_date.year)
    new_params
  end

  private

  def get_report_vacations(vacations)
    vacations.map do |vacation|
      end_date = [Date.parse(params['filter']['end_date']), vacation.end_date].min
      start_date = [Date.parse(params['filter']['start_date']), vacation.start_date].max
      employee_dept_name = if vacation.employee.department.present?
                             vacation.employee.department.name
                           else
                             nil
                           end
      OpenStruct.new(
                       start_date: start_date,
                       end_date: end_date,
                       employee_name: vacation.employee.display_name,
                       employee_dept_name: employee_dept_name,
                       vacation_type: vacation.vacation_type,
                       business_days: (calc_business_days_for_range(start_date, end_date) - ((vacation.half_day && end_date == vacation.end_date) ? 0.5 : 0)),
                       reason: vacation.reason
                     )
    end
  end

  def get_orasi_holiday(day)
    case
    when (day.month == 5 && day.day == 1)
      'Fiscal New Year'
    when day.new_years_day?
      "New Year's Day"
    when day.memorial_day?
      'Memorial Day'
    when day.independence_day?
      'Independence Day'
    when day.labor_day?
      'Labor Day'
    when day.thanksgiving?
      'Thanksgiving Day'
    when day.christmas_eve?
      'Christmas Eve'
    when day.christmas?
      'Christmas Day'
    end
  end

  def filter_params
    allowed_params = %i(start_date end_date department sick vacation floating_holiday other include_pending)
    allowed_params += %i(include_reasons) if current_user.admin?
    params.require(:filter).permit(allowed_params)
  end

  def set_pagination
    @max_pagination_pages = 10
    @next_disabled = @active_page == @page_count - 1
    @prev_disabled = @active_page == 0

    if @active_page > (@max_pagination_pages / 2)
      if @active_page < @page_count - (@max_pagination_pages / 2 - 1)
        @pagination_range = (@active_page - (@max_pagination_pages / 2)..@active_page + (@max_pagination_pages / 2 - 1))
      else
        @pagination_range = ([@page_count - (@max_pagination_pages - 1), 1].max..@page_count)
      end
    else
      @pagination_range = (1..@page_count)
    end
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/views/calendar/_report_form.html.haml
- edit = false if local_assigns[:edit].nil?
- @filter = nil unless edit
= form_for :filter, html: {class: :form, role: :form, id: 'filter-form'}, url: report_calendar_path, method: :get do |f|
  = f.label :start_date, class: 'control-label'
  = f.date_field :start_date, id: "reporting_start_date#{'_edit' if edit}", 'value' => "#{@filter.start_date unless @filter.nil? || edit == false}", class: 'form-control', required: true, placeholder: 'YYYY-MM-DD', pattern: '\d{4}-\d{2}-\d{2}', title: 'YYYY-MM-DD'
  = f.label :end_date, class: 'control-label'
  = f.date_field :end_date, id: "reporting_end_date#{'_edit' if edit}", 'value' => "#{@filter.end_date unless @filter.nil? || edit == false}", class: 'form-control', required: true, placeholder: 'YYYY-MM-DD', pattern: '\d{4}-\d{2}-\d{2}', title: 'YYYY-MM-DD'
  = f.label :department, class: 'control-label'
  = f.select :department, Department.all.collect {|d| [d.name, d.id]}.unshift('Select All'), {include_blank: false}, class: 'form-control'

  #vacation-checkboxes
    - %i(sick vacation floating_holiday other).each do |vacation_type|
      = f.label vacation_type, class: 'control-label'
      = f.check_box vacation_type
    %a.check-all Check all
  #pending-and-reasons-checkboxes
    = f.label 'Include pending?', class: 'control-label'
    = f.check_box :include_pending
    - if current_user && current_user.admin?
      = f.label 'Include reasons?', class: 'control-label'
      = f.check_box :include_reasons
  = f.submit 'Generate Report', class: 'btn btn-primary', 'data-loading-text' => 'Generating...'

app/views/calendar/index.html.erb
<div class="calendar-header">
	<%= form_tag(:calendar,method: :get, id: "calendar-params") do %>
	<div id="calendar-date-select">
		<%= link_to calendar_path(change_month(-1)), class: "month-changer #{'disabled' if @disabled_prev_month}" do %>
			<span class="glyphicon glyphicon-chevron-left"></span>
		<% end %>
		<%= select_tag :month, options_for_select(@all_months,params[:month].blank? ? Date.current.month : params[:month]), class: "form-control" %>
		<%= select_tag :year, options_for_select(@selectable_years, params[:year].blank? ? Date.current.year : params[:year]), class: "form-control" %>
		<%= link_to calendar_path(change_month(1)), class: "month-changer #{'disabled' if @disabled_next_month}" do %>
		<span class="glyphicon glyphicon-chevron-right"></span>
		<% end %>
	</div>
	<div class="btn-group" data-toggle="buttons">
		<% unless @filter_types.length == 1 %>
		<% @filter_types.each do |filter_name| %>
		<%= label_tag nil, class: "btn btn-primary #{"active" if @selected_filter_type == filter_name}" do %>
				<input type="radio" name="filter" value="<%= filter_name %>" <%= "checked" if @selected_filter_type == filter_name %>>
				<% if filter_name == "department" %>
				<%= current_user.department.name %>
				<% else %>
				<%= filter_name.capitalize %>
				<% end %>
		<% end %>
		<% end %>
		<% end %>
	</div>
	<% end %>
</div>
<div class="table-responsive">
	<table class="table" id="vacation-calendar">
		<tr>
			<%# Auto update on starting day. %>
			<% (Date.current.beginning_of_week..Date.current.end_of_week).each do |date| %>
			<th><%= date.strftime("%A") %></th>
			<% end %>
		</tr>
		<% (@starting_date.beginning_of_month.beginning_of_week..@starting_date.end_of_month.end_of_week).each_slice(7) do |week_slice| %>
		<tr>
			<% week_slice.each do |day| %>
			<% i=0 %>
              <td class="calendar-day-cell <%= "company-holiday" if day.is_orasi_holiday? and day.month == @starting_date.month %>">
                <% if day.month == @starting_date.month %>
			<% orasi_holiday = get_orasi_holiday(day) %>
			<div>
				<%= content_tag :span, class: "#{"today" if day == Date.current}" do %>
					<%= day.day %>
				<% end %>
				<%= content_tag :em do %>
					<%= " " + orasi_holiday unless orasi_holiday.blank? or day.month != @starting_date.month %>
				<% end %>
			</div>
			<div>
				<ul class="list-group">
					<% @pdo_times.where(":day >= vacations.start_date and :day <= vacations.end_date",day: day).joins(:employee).order("status ASC, vacation_type ASC, employees.first_name ASC").each do |pdo_date| %>
					<% i += 1 %>
					<%= content_tag :li, class: "list-group-item #{pdo_date.vacation_type.downcase.tr_s(" ","-")} #{"list-group-item-hidden hidden" if i > @max_entries_per_day} #{"calendar-pending-vacation" if pdo_date.status == "Pending"}", title: pdo_date.vacation_type + "#{" (Pending)" if pdo_date.status == "Pending"}", data: {toggle: "tooltip", placement: "right"} do %>
						<%= pdo_date.employee.display_name %><%= " 1/2" if day == pdo_date.end_date and pdo_date.half_day %>
					<% end %>
					<% end %>
					<%= link_to "#{i - @max_entries_per_day} more #{'item'.pluralize(i-@max_entries_per_day)}...", "#", class: "btn btn-link btn-xs more-pdo" if i > @max_entries_per_day %>
					<%= link_to "Collapse", "javascript:void(0)", class: "btn btn-link btn-xs more-pdo hidden" if i > @max_entries_per_day %>
				</ul>
			</div> <% end %> </td>
			<% end %>
		</tr>

		<% end %>
	</table>
</div>
<div>
	<a href="#" class="pull-right" data-toggle="modal" data-target="#modal_1">Legend</a>
    <a href='#' class='pull-right expand-all' style='margin-right: 10px' onClick = 'return false;'>Show All</a>
</div>

<% content_for "modal_header_1" do %>
Legend
<% end %>

<% content_for "modal_content_1" do %>
<ul class="list-group">
	<li class="list-group-item sick">
		Sick
	</li>
	<li class="list-group-item vacation">
		Vacation
	</li>
	<li class="list-group-item floating-holiday">
		Floating Holiday
	</li>
	<li class="list-group-item other">
		Other
	</li>
	<li class="list-group-item sick calendar-pending-vacation">
		Sick (Pending)
	</li>
	<li class="list-group-item vacation calendar-pending-vacation">
		Vacation (Pending)
	</li>
	<li class="list-group-item floating-holiday calendar-pending-vacation">
		Floating Holiday (Pending)
	</li>
  <li class="list-group-item company-holiday vacation calendar-pending-vacation">
    Company Holiday
  </li>
</ul>
<div class="modal-footer">
	<%= button_tag "Close", type: "button", class: "btn btn-default", data: {dismiss: "modal"}%>
</div>
<% end %>
<%= render 'modals/modal_group' %>

app/views/calendar/report.csv.erb
Name,Start Date,End Date,Department,Vacation Type,Business Days
<% @report_vacations.each do | vacation | %>
<%=vacation.employee_name%>,<%=vacation.start_date%>,<%=vacation.end_date%>,<%=vacation.employee_dept_name%>,<%=vacation.vacation_type%>,<%=vacation.business_days%><%= ",#{vacation.reason}" if @include_reasons %>
<% end %>

app/views/calendar/report.html.haml
= render 'notification_section'
#download-link-header
  %span
    Download
    = link_to 'CSV', report_calendar_path(params.merge(format: :csv))
    |
    = link_to 'JSON', report_calendar_path(params.merge(format: :json))
  .btn-group.pull-right
    = button_tag 'New Report', class: 'btn btn-sm btn-primary', data: { toggle: 'modal', target: '#vacation_reporting_modal' }
    = button_tag 'Edit Report', class: 'btn btn-sm btn-primary', data: { toggle: 'modal', target: '#vacation_reporting_modal_edit' }
  .clearfix
%table.table
  %tr
    - ['Name', 'Start Date', 'End Date', 'Department', 'Vacation Type', 'Business Days'].each do |header|
      %th
        = link_to header, report_calendar_path(params.merge(sort: header.downcase.tr_s(' ','_'), rev: params[:rev]!='true', filter: params['filter']))
        = render partial: 'application/ascending_descending_icon_nojs', locals: { predicate: params['sort'].present? && params['sort'].humanize.downcase == header.downcase, forward: params[:rev] != 'true', numeric: ['Start Date', 'End Date', 'Business Days'].include?(header) }
    - if @include_reasons
      %th= link_to 'Reason', report_calendar_path(params.merge(sort: 'Reason', rev: params[:rev]!='true', filter: params['filter']))
    - @report_vacations.each do |vacation|
      %tr
        %td= vacation.employee_name
        %td= vacation.start_date
        %td= vacation.end_date
        %td= vacation.employee_dept_name
        %td= vacation.vacation_type
        %td= vacation.business_days
        - if @include_reasons
          %td= vacation.reason
- if @page_count > 1
  .pagination
    %ul.pagination
      %li{ class: ('disabled' if @prev_disabled) }
        = link_to '&laquo;'.html_safe, report_calendar_path(params.merge('pgn' => @active_page))

      - @pagination_range.first(@max_pagination_pages).each do |num|
        %li{ class: ('active' if @active_page == num - 1) }
          = link_to num, report_calendar_path(params.merge('pgn' => num))

      %li{ class: ('disabled' if @next_disabled) }
        = link_to '&raquo;'.html_safe, report_calendar_path(params.merge('pgn' => @active_page + 2))

= render partial: 'vacation_reporting_modal', locals: {edit: true}