config/routes.rb
BlueSource::Application.routes.draw do
  get 'api/subordinates'
  get 'api/manager'

  resources :titles

  get 'admin/index'
  namespace :admin do
    resources :departments, only: :index
    resources :titles
  end

  resources :employees do
    resources :vacations, only: [:index, :create, :update, :destroy] do
      collection do
        get 'view'
        post 'requests'
      end
      member do
        delete 'cancel'
      end
    end
    resources :project_histories, path: 'projects'
    patch 'preferences'
  end

  resources :departments, only: [:destroy, :new, :create, :update, :edit] do
    get 'sub_departments'
    get 'employees'
  end

  resources :projects, only: [:index, :show, :create, :update, :edit] do
    get 'leads'
  end

  get 'login', to: 'welcome#login', as: :login
  get 'logout', to: 'welcome#logout', as: :logout
  post 'login', to: 'welcome#validate', as: :check_login
  post 'issue', to: 'welcome#issue', as: :issue
  post 'search', to: 'welcome#search_employee', as: :search
  post 'login_issue', to: 'welcome#login_issue', as: :login_issue

  resource :directory, only: [:show], controller: 'directory' do
    resources :employees, only: [:index], action: 'directory'
  end

  resource :calendar, only: [:index] do
    get '/', to: 'calendar#index'
    get '/report', to: 'calendar#report'
  end

  root 'employees#index'

end

app/models/title.rb
class Title < ActiveRecord::Base
  has_many :employees, dependent: :nullify
  validates :name, uniqueness: { case_sensitive: false }, presence: true
end

app/controllers/admin/titles_controller.rb
class Admin::TitlesController < ApplicationController
  before_action :require_login
  before_action :must_be_company_admin, except: [:sub_departments, :employees]
  before_action :set_title, only: [:show, :edit, :update, :destroy]

  # GET /titles
  # GET /titles.json
  def index
    @titles = Title.order(name: :asc)
  end

  # GET /titles/1.json
  def show
  end

  # GET /titles/new
  def new
    @title = Title.new
  end

  # GET /titles/1/edit
  def edit
  end

  # POST /titles
  # POST /titles.json
  def create
    @title = Title.new(title_params)

    respond_to do |format|
      if @title.save
        format.html { redirect_to admin_titles_path, flash: { success: 'Title successfully created.' } }
        format.json { render action: 'show', status: :created, location: @title }
      else
        format.html { render action: 'new' }
        format.json { render json: admin_title_path(@title).errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titles/1
  # PATCH/PUT /titles/1.json
  def update
    respond_to do |format|
      if @title.update(title_params)
        format.html { redirect_to admin_titles_path(@title), flash: { success: 'Title successfully updated.' } }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: admin_title_path(@title).errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titles/1
  # DELETE /titles/1.json
  def destroy
    @title.destroy
    respond_to do |format|
      format.html { redirect_to admin_titles_url, flash: { success: 'Title successfully deleted.' } }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_title
    @title = Title.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def title_params
    params.require(:title).permit(:name)
  end

  def must_be_company_admin
    unless current_user.role == 'Company Admin' || current_user.sys_admin?
      redirect_to :root, flash: { error: 'You do not have sys admin privileges.' }
    end
  end
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/admin/titles/_form.html.erb
<%= form_for(@title, url: admin_title_path(@title)) do |f| %>
  <% if @title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@title.errors.count, "error") %> prohibited this title from being saved:</h2>

      <ul>
      <% @title.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/titles/edit.html.erb
<h1>Editing title</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_titles_path %>

app/views/admin/titles/index.html.erb
<h1>Listing titles</h1>
<%= render "notification_section" %>
<% unless @titles.count == 0 %>
<table class="table table-responsive table-bordered">
	<thead>
		<tr>
			<th>Title</th>
		</tr>
	</thead>

	<tbody>
		<% @titles.each do |title| %>
		<tr>
			<td> <%= title.name %>
			<div class="pull-right">
				<%= link_to edit_admin_title_path(title) do %>
					<span class="glyphicon glyphicon-pencil"></span>
				<% end %>
				<%= link_to admin_title_path(title), method: :delete, data: { confirm: 'Are you sure?' } do %>
					<span class="glyphicon glyphicon-trash"></span>
				<% end %>
			</div></td>
		</tr>
		<% end %>
	</tbody>
</table>
<% end %>
<br>

<%= link_to 'New Title', new_admin_title_path %>

app/views/admin/titles/new.html.erb
<h1>New title</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_titles_path %>